import 'package:hive/hive.dart';
part 'post_model.g.dart'; // This will be generated by build_runner

@HiveType(typeId: 0)
class Post extends HiveObject {
  @HiveField(0)
  final String imagePath; // Store path instead of File for Hive compatibility

  @HiveField(1)
  final String caption;

  Post({required this.imagePath, required this.caption});
}
